auto: true
server: false
lsi: false
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
paginate: 1
category_dir: topics
category_title_prefix: 
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp"]
destination: public